version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "1.30.0"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "php"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/CyberdyneHQ/Gigarepo"

[[transformers]]
name = "black"

[[transformers]]
name = "rustfmt"

[[transformers]]
name = "rubocop"

[[transformers]]
name = "php-cs-fixer"

[[transformers]]
name = "prettier"

[[transformers]]
name = "dotnet-format"

[[transformers]]
name = "google-java-format"

[[transformers]]
name = "gofmt"